version: '3'
services:
        mysql1:
                image: mysql:latest
                restart: always
                ports:
                        - "3306:3306"
                environment:
                        - MYSQL_ROOT_PASSWORD=pucsd
                        - MYSQL_DATABASE=PucsdStudents
                        - MYSQL_USER=pucsd
                        - MYSQL_PASSWORD=pucsd
                volumes:
                        - ./test1.sql:/docker-entrypoint-initdb.d/test.sql
                
        mysql2:
                image: mysql:latest
                restart: always
                ports:
                        - "3307:3306"
                environment:
                        - MYSQL_ROOT_PASSWORD=pucsd
                        - MYSQL_DATABASE=PucsdStudents
                        - MYSQL_USER=pucsd
                        - MYSQL_PASSWORD=pucsd
                volumes:
                        - ./test2.sql:/docker-entrypoint-initdb.d/test.sql
 
        mysql3:
                image: mysql:latest
                restart: always
                ports:
                        - "3308:3306"
                environment:
                        - MYSQL_ROOT_PASSWORD=pucsd
                        - MYSQL_DATABASE=PucsdStudents
                        - MYSQL_USER=pucsd
                        - MYSQL_PASSWORD=pucsd
                volumes:
                        - ./test3.sql:/docker-entrypoint-initdb.d/test.sql

